export type CommandsType = {
    conference: string
    logo: string
    name: string
    wins: number
    losses: number
    winRate: string
    gamesBack: string
    confRecord: string
    homeRecord: string
    awayRecord: string
    recordLastTenGames: string
    currentStreak: string
}

export const commandsInfo: CommandsType[] = [
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/GDJBo7eEF8EO5-kDHVpdqw_48x48.png",
        name: "Селтикс",
        wins: 41,
        losses: 12,
        winRate: ".774",
        gamesBack: "-",
        confRecord: "28-6",
        homeRecord: "25-3",
        awayRecord: "16-9",
        recordLastTenGames: "8-2",
        currentStreak: "W4",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/NAlGkmv45l1L-3NhwVhDPg_48x48.png",
        name: "Кавальерс",
        wins: 35,
        losses: 17,
        winRate: ".673",
        gamesBack: "5.5",
        confRecord: "23-11",
        homeRecord: "18-9",
        awayRecord: "17-8",
        recordLastTenGames: "9-1",
        currentStreak: "L1",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/Wd6xIEIXpfqg9EZC6PAepQ_48x48.png",
        name: "Бакс",
        wins: 35,
        losses: 19,
        winRate: ".648",
        gamesBack: "6.5",
        confRecord: "25-12",
        homeRecord: "23-6",
        awayRecord: "12-13",
        recordLastTenGames: "4-6",
        currentStreak: "W2",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/-rf7eY39l_0V7J4ekakuKA_48x48.png",
        name: "Никс",
        wins: 34,
        losses: 21,
        winRate: ".611",
        gamesBack: "8.5",
        confRecord: "22-11",
        homeRecord: "19-8",
        awayRecord: "14-13",
        recordLastTenGames: "6-4",
        currentStreak: "L3",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/US6KILZue2D5766trEf0Mg_48x48.png",
        name: "Севенти Сиксерс",
        wins: 32,
        losses: 21,
        winRate: ".604",
        gamesBack: "9.0",
        confRecord: "21-13",
        homeRecord: "17-10",
        awayRecord: "15-11",
        recordLastTenGames: "3-7",
        currentStreak: "W2",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/p69oiJ4LDsvCJUDQ3wR9PQ_48x48.png",
        name: "Мэджик",
        wins: 29,
        losses: 24,
        winRate: ".547",
        gamesBack: "12.0",
        confRecord: "19-14",
        homeRecord: "17-7",
        awayRecord: "12-17",
        recordLastTenGames: "6-4",
        currentStreak: "W2",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/andumiE_wrpDpXvUgqCGYQ_48x48.png",
        name: "Пэйсерс",
        wins: 30,
        losses: 25,
        winRate: ".545",
        gamesBack: "12.0",
        confRecord: "23-14",
        homeRecord: "17-11",
        awayRecord: "13-14",
        recordLastTenGames: "5-5",
        currentStreak: "L1",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/0nQXN6OF7wnLY3hJz8lZJQ_48x48.png",
        name: "Хит",
        wins: 28,
        losses: 25,
        winRate: ".528",
        gamesBack: "13.0",
        confRecord: "20-16",
        homeRecord: "15-13",
        awayRecord: "12-13",
        recordLastTenGames: "4-6",
        currentStreak: "L1",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/ofjScRGiytT__Flak2j4dg_48x48.png",
        name: "Буллз",
        wins: 26,
        losses: 28,
        winRate: ".481",
        gamesBack: "15.5",
        confRecord: "15-18",
        homeRecord: "15-12",
        awayRecord: "11-16",
        recordLastTenGames: "5-5",
        currentStreak: "W1",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/pm5l5mtY1elOQAl9ZEcm2A_48x48.png",
        name: "Хокс",
        wins: 24,
        losses: 30,
        winRate: ".444",
        gamesBack: "17.5",
        confRecord: "14-22",
        homeRecord: "13-15",
        awayRecord: "11-15",
        recordLastTenGames: "6-4",
        currentStreak: "L1",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/iishUmO7vbJBE7iK2CZCdw_48x48.png",
        name: "Нетс",
        wins: 21,
        losses: 31,
        winRate: ".404",
        gamesBack: "19.5",
        confRecord: "14-15",
        homeRecord: "13-16",
        awayRecord: "8-15",
        recordLastTenGames: "4-6",
        currentStreak: "W1",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/745IgW4NSvnRxg-W9oczmQ_48x48.png",
        name: "Рэпторс",
        wins: 19,
        losses: 35,
        winRate: ".352",
        gamesBack: "22.5",
        confRecord: "12-22",
        homeRecord: "11-15",
        awayRecord: "8-20",
        recordLastTenGames: "3-7",
        currentStreak: "L2",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/ToeKy5-TrHAnTCl-qhuuHQ_48x48.png",
        name: "Хорнетс",
        wins: 12,
        losses: 41,
        winRate: ".226",
        gamesBack: "29.0",
        confRecord: "8-25",
        homeRecord: "7-21",
        awayRecord: "5-20",
        recordLastTenGames: "2-8",
        currentStreak: "W2",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/NBkMJapxft4V5kvufec4Jg_48x48.png",
        name: "Уизардс",
        wins: 9,
        losses: 44,
        winRate: ".170",
        gamesBack: "32.0",
        confRecord: "6-31",
        homeRecord: "3-23",
        awayRecord: "6-21",
        recordLastTenGames: "2-8",
        currentStreak: "L7",
    },
    {
        conference: "Eastern",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/qvWE2FgBX0MCqFfciFBDiw_48x48.png",
        name: "Пистонс",
        wins: 8,
        losses: 44,
        winRate: ".154",
        gamesBack: "32.5",
        confRecord: "5-25",
        homeRecord: "4-23",
        awayRecord: "4-21",
        recordLastTenGames: "4-6",
        currentStreak: "L1",
    },

    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/21Zm6e_zGiWXsaLCQyjVig_48x48.png",
        name: "Тимбервулвз",
        wins: 37,
        losses: 16,
        winRate: ".698",
        gamesBack: "-",
        confRecord: "25-8",
        homeRecord: "19-5",
        awayRecord: "18-11",
        recordLastTenGames: "7-3",
        currentStreak: "W2",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/b4bJ9zKFBDykdSIGUrbWdw_48x48.png",
        name: "Тандер",
        wins: 36,
        losses: 17,
        winRate: ".697",
        gamesBack: "1.0",
        confRecord: "22-13",
        homeRecord: "21-6",
        awayRecord: "15-11",
        recordLastTenGames: "7-3",
        currentStreak: "L1",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/F36nQLCQ2FND3za-Eteeqg_48x48.png",
        name: "Клипперс",
        wins: 35,
        losses: 17,
        winRate: ".673",
        gamesBack: "1.5",
        confRecord: "21-13",
        homeRecord: "20-6",
        awayRecord: "15-11",
        recordLastTenGames: "7-3",
        currentStreak: "L1",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/9wPFTOxV_zP1KmRRggJNqQ_48x48.png",
        name: "Наггетс",
        wins: 36,
        losses: 18,
        winRate: ".667",
        gamesBack: "1.5",
        confRecord: "20-12",
        homeRecord: "21-4",
        awayRecord: "15-14",
        recordLastTenGames: "6-4",
        currentStreak: "L2",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/JCQO978-AWbg00TQUNPUVg_48x48.png",
        name: "Пеликанс",
        wins: 32,
        losses: 12,
        winRate: ".593",
        gamesBack: "5.5",
        confRecord: "23-18",
        homeRecord: "15-10",
        awayRecord: "17-12",
        recordLastTenGames: "6-4",
        currentStreak: "W2",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/pRr87i24KHWH0UuAc5EamQ_48x48.png",
        name: "Финикс",
        wins: 31,
        losses: 22,
        winRate: ".585",
        gamesBack: "6.0",
        confRecord: "18-15",
        homeRecord: "16-11",
        awayRecord: "15-11",
        recordLastTenGames: "6-4",
        currentStreak: "L1",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/wkCDHakxEThLGoZ4Ven48Q_48x48.png",
        name: "Тандер",
        wins: 30,
        losses: 22,
        winRate: ".577",
        gamesBack: "6.5",
        confRecord: "19-14",
        homeRecord: "15-9",
        awayRecord: "15-13",
        recordLastTenGames: "6-4",
        currentStreak: "L1",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/xxxlj9RpmAKJ9P9phstWCQ_48x48.png",
        name: "Маверикс",
        wins: 31,
        losses: 23,
        winRate: ".574",
        gamesBack: "6.5",
        confRecord: "19-18",
        homeRecord: "16-13",
        awayRecord: "15-10",
        recordLastTenGames: "7-3",
        currentStreak: "W5",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/4ndR-n-gall7_h3f7NYcpQ_48x48.png",
        name: "Лейкерс",
        wins: 28,
        losses: 26,
        winRate: ".519",
        gamesBack: "9.5",
        confRecord: "19-17",
        homeRecord: "18-9",
        awayRecord: "10-17",
        recordLastTenGames: "6-4",
        currentStreak: "W1",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/ovwlyYHRKZ90s7zn_qlMCg_48x48.png",
        name: "Уорриорз",
        wins: 26,
        losses: 25,
        winRate: ".510",
        gamesBack: "10.0",
        confRecord: "14-19",
        homeRecord: "14-13",
        awayRecord: "12-12",
        recordLastTenGames: "7-3",
        currentStreak: "W5",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/xxdtYBIrtmG-BKEdbxpTBw_48x48.png",
        name: "Юта",
        wins: 26,
        losses: 28,
        winRate: ".481",
        gamesBack: "11.5",
        confRecord: "13-20",
        homeRecord: "17-8",
        awayRecord: "9-20",
        recordLastTenGames: "4-6",
        currentStreak: "L2",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/zhO6MIB1UzZmtXLHkJQBmg_48x48.png",
        name: "Рокетс",
        wins: 24,
        losses: 29,
        winRate: ".453",
        gamesBack: "13.0",
        confRecord: "16-13",
        homeRecord: "19-9",
        awayRecord: "5-20",
        recordLastTenGames: "4-6",
        currentStreak: "W1",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/3ho45P8yNw-WmQ2m4A4TIA_48x48.png",
        name: "Гриззлис",
        wins: 18,
        losses: 36,
        winRate: ".333",
        gamesBack: "19.5",
        confRecord: "12-24",
        homeRecord: "5-20",
        awayRecord: "13-16",
        recordLastTenGames: "1-9",
        currentStreak: "L9",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/_bgagBCd6ieOIt3INWRN_w_48x48.png",
        name: "Трэйл Блэйзерс",
        wins: 15,
        losses: 37,
        winRate: ".288",
        gamesBack: "21.5",
        confRecord: "6-29",
        homeRecord: "9-15",
        awayRecord: "6-22",
        recordLastTenGames: "3-7",
        currentStreak: "L4",
    },
    {
        conference: "Western",
        logo: "https://ssl.gstatic.com/onebox/media/sports/logos/FKwMB_85FlZ_7PTt1f7hjQ_48x48.png",
        name: "Спёрс",
        wins: 11,
        losses: 43,
        winRate: ".204",
        gamesBack: "26.5",
        confRecord: "7-21",
        homeRecord: "5-21",
        awayRecord: "6-22",
        recordLastTenGames: "3-7",
        currentStreak: "W1",
    },
];
